# Generated by Django 6.0.1 on 2026-02-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(db_index=True, max_length=254)),
                ('ticker', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('qty', models.IntegerField(default=0)),
                ('avg_price', models.FloatField(default=0.0)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user_email', 'ticker')},
            },
        ),
    ]
