# Generated by Django 6.0.1 on 2026-02-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0003_transaction_watchlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_assessment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
