# Generated by Django 6.0.1 on 2026-03-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0006_papertrade_watchlistalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verification_token',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verification_token_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
